Update service name

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -170,7 +170,13 @@ stages:
       EOF"
 
       echo "Checking if application is ready..."
-      export KUBE_SERVICE_NAME=${IMAGE_NAME}
+
+      # Get kube service name from metadata name in service file
+      export KUBE_SERVICE_NAME=$(yq read $SERVICE_FILE metadata.name)
+      if [ "$KUBE_SERVICE_NAME" == "null" ]; then
+          echo "ERROR: no service name found in service file, $SERVICE_FILE"
+          exit 1
+      fi
 
       for ITERATION in {1..30}
       do
@@ -222,8 +228,8 @@ stages:
     - name: COLIGO_PROJECT
       value: ${COLIGO_PROJECT}
       type: text
-    - name: IMAGE_NAME
-      value: ${IMAGE_NAME}
+    - name: SERVICE_FILE
+      value: service.yaml
       type: text
     deploy_type: kubernetes
     target:
@@ -232,12 +238,17 @@ stages:
       resource_group: ${COLIGO_RESOURCE_GROUP}
       kubernetes_cluster: dummy-value
     script: |-
-      export KUBE_SERVICE_NAME=${IMAGE_NAME}
-
       ibmcloud plugin install coligo
 
       echo "Load Kube config"
       eval "$(ibmcloud coligo target --name ${COLIGO_PROJECT} | grep export)"
+
+      # Get kube service name from metadata name in service file
+      export KUBE_SERVICE_NAME=$(yq read $SERVICE_FILE metadata.name)
+      if [ "$KUBE_SERVICE_NAME" == "null" ]; then
+          echo "ERROR: no service name found in service file, $SERVICE_FILE"
+          exit 1
+      fi
 
       kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status.url'
       TEMP_URL=$( kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status.url' )
